### Chapter 2- Vector part 1 

Vectors has 2 important characteristics: 

1. Dimensionality: the number os numbers in the vector
2. Orientation: whether the vector is in column orientation(standing up tall) or row orientation(laying flat and wide)

In [ ]:
import numpy as np

asList =[1,2,3]
asArray=np.array([1,2,3]) #1D array
rowVector= np.array([[1,2,3]]) #row
colVector=np.array([[1],[2],[3]]) #column

# Inspecting the shape of the variables:
print(f'aslist: {np.shape(asList)}')
print(f'aslist: {asArray.shape}')
print(f'aslist: {rowVector.shape}')
print(f'aslist: {colVector.shape}')


## Geometry of Vectors

## Operations on Vectos

1. Adding 2 vectors
2. Subtracting 2 vectors

In [14]:
# Adding vectors require them to be in a same dimensions
u = np.array([1,2,3])
v=np.array([4,5,6])
w=np.array([1,2,3,4])
uPlusv= u + v
try: 
    uPlusw= u + w
except(ValueError):
    print("Can\'t add 2 vectors of different dimension")

# Does vector orientation matter for vector addition:
result= rowVector + colVector
print(result)



Can't add 2 vectors of different dimension
[[2 3 4]
 [3 4 5]
 [4 5 6]]


## In Python you can only add Vectors together if they have the same dimension and orientation

In [12]:
## Vector-Scalar Multiplication 
print(u)
print(u * 3)

## The Zeros Vector
## Asterisk operator for array and list
s=2.0
a=[1,2,3]
b=np.array(a)
try :
    print(a*s)
except(TypeError):
    print('Can\'t multiply list by an integer value')
print(b*s)

[1 2 3]
[3 6 9]
Can't multiply list by a integer value
[2. 4. 6.]


In [40]:
## Vector Broadcasting in Python

v = np.array([[1,2,3]]).T
w=np.array([[10,20]])
print(v+w)

[[11 21]
 [12 22]
 [13 23]]


In [ ]:
## Vector Magnitude and Unit Vectors 
A = np.array([1,2,3,4,5])
print(A)
print(A_1)
# To find the dimensionality use len()
print(len(A))

# To find the geometric length or the norm use norm 
print(np.linalg.norm(A))

unit_vector = (1/np.linalg.norm(A)) * A 
print(unit_vector)
# The magnitude of a vector also call the geometric length or the norm is the distance from the tail to head of a vector.

In [39]:
## Vector Dot Product or inner product 
## The dot product is a single number that provides information about the relationship between two vectors

v = np.array([1,2,3,4])
m = np.array([4,5,6,7])
dot_product_a_b= np.dot(v,m)
print(dot_product_a_b)

#Geometry of the Dot Product

## Orthogonal Vectors has a Zero Dot Product

## Hadamard Multiplication or element-wise multiplication
a= np.array([5,4,8,2])
b=np.array([1,0,3,0.5]).T
print(a*b)




60
[ 5.  0. 24.  1.]


### Outer Product

In [38]:
a = np.array([1,2,3])
b=np.array([4,5,6])

print(np.outer(a,b))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


Orthogonal Vector Decomposition