## Row Reduction and LU Decomposition



System of Equations



In [ ]:
import numpy as np

A = np.random.randn(4,4)


In [4]:
## Row reduction

## Gauss-Jordan Elimination
import sympy as sym
import numpy as np

M = np.array([[1,1,4],[-1/2,1,2]])
symMat=sym.Matrix(M)

symMat.rref()[0]




Matrix([
[1, 0, 1.33333333333333],
[0, 1, 2.66666666666667]])

In [6]:
## LU Decompisition
import scipy.linalg

A = np.array([[2,2,4],[1,0,3],[2,1,2]])
_,L,U = scipy.linalg.lu(A)

print(f'L : {L}')
print(f'U: {U}')
print(f'Permutation: {_}')

L : [[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  1.  1. ]]
U: [[ 2.  2.  4.]
 [ 0. -1.  1.]
 [ 0.  0. -3.]]
Permutation: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
## Row Swaps via Permutation Matrices 

## Full from of LU decomposition is 
## PA = LU
## A = P.TLU
# Permutation matrix are orthogonal matrix 
