In [2]:
import numpy as np

## Chapter 9 
## Orthogonal Matrices and QR Decomposition


## Orthogonal Matrices:

# 1 . All columns are pair-wise orthogonal
# 2. The norm of each column is exactly 1 

# The inverse of an orthogonal matrix is its transpose


Q1 = np.array([[1,-1],[1,1]]) / np.sqrt(2)
Q2 = np.array([[1,2,2],[2,1,-2],[-2,2,-1]]) / 3

print(Q1.T@Q1)
print(Q2.T@Q2)




[[1.00000000e+00 2.23711432e-17]
 [2.23711432e-17 1.00000000e+00]]
[[1.00000000e+00 2.46716228e-17 1.54197642e-17]
 [2.46716228e-17 1.00000000e+00 1.23358114e-17]
 [1.54197642e-17 1.23358114e-17 1.00000000e+00]]


Gram-Schmidt 



The Gram-Schmidt procedure is a way to transform a nonorthogonal matrix into an orthogonal matrix.

In [5]:
## Making QR decomposition

A = np.random.randn(3,3)
Q,R = np.linalg.qr(A)
print(Q)
print(R)
print(A)
print(Q@R)

[[-0.9969992   0.03795515  0.06746845]
 [-0.067584   -0.00176814 -0.99771202]
 [-0.03774901 -0.99927788  0.004328  ]]
[[-1.08371112 -1.04654184  0.68939426]
 [ 0.          0.62740285  0.44465055]
 [ 0.          0.          0.65749457]]
[[ 1.08045913  1.06721455 -0.62608861]
 [ 0.07324154  0.06962015 -0.70336847]
 [ 0.04090902 -0.58744387 -0.46750778]]
[[ 1.08045913  1.06721455 -0.62608861]
 [ 0.07324154  0.06962015 -0.70336847]
 [ 0.04090902 -0.58744387 -0.46750778]]
