Marices, part 1

In [2]:
## Creating and Visualizing Matrices in Numpy
import numpy as np

## Creating a matrix with elements range from 1 to 60, which 6 rows and 10 columns:
A = np.arange(60).reshape(6,10)
sub_matrix=A[1:4:1,0:5:1]
sub_matrix

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [10]:
## Special Matrices

## Random numbers matrix

A = np.random.randn(3,3)
A 

## Square matrix: 
### Diagonal matrix:
B =np.diag(np.array([1,2,3]))
B

## Triangular Matrix: 
#A triangular matrix contains all zeros either above or below the main diagonal. The matrix is called upper triangular if the nonzero elements are above the diagonal and lower triangular if the nonzero elements are below the diagonal.
upper_triangular_matrix= np.triu(np.array([1,2,3]))
lower_triagular_matrix=np.tril(np.array([4,5,6]))

print(upper_triangular_matrix)
print(lower_triagular_matrix)

## Identity matrix
identity_matrix = np.eye(5,5,dtype=int)
print(identity_matrix)

## Zeros matrix
zeros_matrix= np.zeros((3,5))
print(zeros_matrix)




[[1 2 3]
 [0 2 3]
 [0 0 3]]
[[4 0 0]
 [4 5 0]
 [4 5 6]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
## Shifting of a matrix

A = np.array([[4,5,1],[0,1,11],[4,9,7]])
s=6
A + s # not shifting
A + s*np.eye(len(A)) # shifting

[[ 4  0  4]
 [ 5  1  9]
 [ 1 11  7]]


array([[10.,  0.,  4.],
       [ 5.,  7.,  9.],
       [ 1., 11., 13.]])

In [ ]:
## Element-wise or Hadamard multiplication of matrix 
A*B
np.multiply(A,B)


In [24]:
## Standard Matrix Multiplication

A = np.arange(1,10).reshape(3,3)
B= np.arange(1,10).reshape(3,3)
print(A@B)
C = np.dot(A,B)
print(C)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
